-- MySQL Script generated by MySQL Workbench
-- ven 08 oct 2021 12:15:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema monCVrevision
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema monCVrevision
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monCVrevision` ;
USE `monCVrevision` ;

-- -----------------------------------------------------
-- Table `monCVrevision`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monCVrevision`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monCVrevision`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monCVrevision`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role-fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `role-fk_idx` (`role-fk` ASC) VISIBLE,
  CONSTRAINT `role-fk`
    FOREIGN KEY (`role-fk`)
    REFERENCES `monCVrevision`.`role` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monCVrevision`.`ul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monCVrevision`.`ul` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `contentUl` VARCHAR(100) NOT NULL,
  `contentLi` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monCVrevision`.`dd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monCVrevision`.`dd` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `contentDd` VARCHAR(45) NOT NULL,
  `contentDt` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monCVrevision`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monCVrevision`.`section` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `author-fk` INT UNSIGNED NOT NULL,
  `ul-fk` INT UNSIGNED NOT NULL,
  `dd-fk` INT UNSIGNED NOT NULL,
  `date` DATETIME NOT NULL DEFAULT  CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `author-fk_idx` (`author-fk` ASC) VISIBLE,
  INDEX `ul-fk_idx` (`ul-fk` ASC) VISIBLE,
  INDEX `dd-fk_idx` (`dd-fk` ASC) VISIBLE,
  CONSTRAINT `author-fk`
    FOREIGN KEY (`author-fk`)
    REFERENCES `monCVrevision`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ul-fk`
    FOREIGN KEY (`ul-fk`)
    REFERENCES `monCVrevision`.`ul` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `dd-fk`
    FOREIGN KEY (`dd-fk`)
    REFERENCES `monCVrevision`.`dd` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
